export const htmlTopics = [
  "HTML Attributes",
  "HTML Headings",
  "HTML Paragraphs",
  "HTML Styles",
  "HTML Formatting",
  "HTML Quotations",
  "HTML Comments",
  "HTML Colors",
  "HTML CSS",
  "HTML Links",
  "HTML Images",
  "HTML Favicon",
  "HTML Page Title",
  "HTML Classes",
  "HTML Id",
  "HTML Tables",
  "HTML Lists",
  "HTML Block & Inline",
  "HTML Div",
  "HTML Layout",
  "HTML Responsive",
  "HTML Semantics",
  "HTML Style Guide",
  "HTML Forms",
  "HTML Form Attributes",
  "HTML Form Elements",
  "HTML Input Types",
  "HTML Input Attributes",
  "Input Form Attributes",
  "HTML File Paths",
  "HTML JavaScript",
  "HTML Events",
  "HTML Canvas",
  "HTML SVG",
  "HTML Media",
  "HTML Video",
  "HTML Audio",
  "HTML Plug-ins",
  "HTML YouTube",
  "HTML Web APIs",
  "HTML Geolocation",
  "HTML Drag and Drop",
  "HTML Web Storage",
  "HTML Web Workers",
  "HTML SSE",
  "HTML Entities",
  "HTML Symbols",
  "HTML Emojis",
  "HTML Charsets",
  "HTML Character Sets",
  "HTML URL Encode",
  "HTML Lang Codes",
  "HTML Doctypes",
  "HTML vs. XHTML",
  "HTML Browser Support",
  "HTML Tag List",
  "HTML Global Attributes",
  "HTTP Messages",
  "HTTP Methods",
  "PX to EM Converter",
  "Keyboard Shortcuts",
  "HTML Meta Tags",
  "HTML Loading Attribute",
  "HTML Picture Element",
  "HTML Noscript",
  "HTML Custom Data Attributes",
  "HTML Deprecated Tags",
  "HTML Code Snippets",
  "HTML Best Practices",
  "HTML Tips and Tricks",
  "HTML Validation",
  "HTML Testing Tools",
  "HTML SEO Basics",
  "HTML for Email",
  "HTML ARIA Roles",
  "HTML Forms with Flexbox",
  "HTML Components with Web Components",
  "HTML Dark Mode Techniques"
];
