export const JavaScriptTopics = [
  "JS Variables",
  "JS Let",
  "JS Const",
  "JS Operators",
  "JS Arithmetic",
  "JS Assignment",
  "JS Data Types",
  "JS Functions",
  "JS Objects",
  "JS Object Properties",
  "JS Object Methods",
  "JS Object Display",
  "JS Object Constructors",
  "JS Events",
  "JS Strings",
  "JS String Methods",
  "JS String Search",
  "JS String Templates",
  "JS Numbers",
  "JS BigInt",
  "JS Number Methods",
  "JS Number Properties",
  "JS Arrays",
  "JS Array Methods",
  "JS Array Search",
  "JS Array Sort",
  "JS Array Iteration",
  "JS Array Const",
  "JS Dates",
  "JS Date Formats",
  "JS Date Get Methods",
  "JS Date Set Methods",
  "JS Math",
  "JS Random",
  "JS Booleans",
  "JS Comparisons",
  "JS If Else",
  "JS Switch",
  "JS Loop For",
  "JS Loop For In",
  "JS Loop For Of",
  "JS Loop While",
  "JS Break",
  "JS Iterables",
  "JS Sets",
  "JS Set Methods",
  "JS Maps",
  "JS Map Methods",
  "JS Typeof",
  "JS Type Conversion",
  "JS Destructuring",
  "JS Bitwise",
  "JS RegExp",
  "JS Precedence",
  "JS Errors",
  "JS Scope",
  "JS Hoisting",
  "JS Strict Mode",
  "JS this Keyword",
  "JS Arrow Function",
  "JS Classes",
  "JS Modules",
  "JS JSON",
  "JS Debugging",
  "JS Mistakes",
  "JS Performance",
  "JS Reserved Words",
  "JS History",
  "Object Definitions",
  "Object Prototypes",
  "Object Methods",
  "Object Properties",
  "Object Get / Set",
  "Object Protection",
  "Function Definitions",
  "Function Parameters",
  "Function Invocation",
  "Function Call",
  "Function Apply",
  "Function Bind",
  "Function Closures",
  "Class Intro",
  "Class Inheritance",
  "Class Static",
  "JS Callbacks",
  "JS Asynchronous",
  "JS Promises",
  "JS Async/Await",
  "DOM Methods",
  "DOM Document",
  "DOM Elements",
  "DOM HTML",
  "DOM Forms",
  "DOM CSS",
  "DOM Animations",
  "DOM Events",
  "DOM Event Listener",
  "DOM Navigation",
  "DOM Nodes",
  "DOM Collections",
  "DOM Node Lists",
  "JS Window",
  "JS Screen",
  "JS Location",
  "JS History",
  "JS Navigator",
  "JS Popup Alert",
  "JS Timing",
  "JS Cookies",
  "Web API Intro",
  "Web Forms API",
  "Web History API",
  "Web Storage API",
  "Web Worker API",
  "Web Fetch API",
  "Web Geolocation API",
  "AJAX Intro",
  "AJAX XMLHttp",
  "AJAX Request",
  "AJAX Response",
  "AJAX XML File",
  "AJAX PHP",
  "AJAX ASP",
  "AJAX Database",
  "AJAX Applications",
  "AJAX Examples",
  "JSON Intro",
  "JSON Syntax",
  "JSON vs XML",
  "JSON Data Types",
  "JSON Parse",
  "JSON Stringify",
  "JSON Objects",
  "JSON Arrays",
  "JSON Server",
  "JSON PHP",
  "JSON HTML",
  "JSON JSONP",
  "jQuery Selectors",
  "jQuery HTML",
  "jQuery CSS",
  "jQuery DOM",
  "JS Graphics",
  "JS Canvas",
  "JS Plotly",
  "JS Chart.js",
  "JS Google Chart",
  "JS D3.js",
  "JS Examples",
  "JS HTML DOM",
  "JS HTML Input",
  "JS HTML Objects",
  "JS HTML Events",
  "JavaScript Objects",
]
