export const nodeJsTopics = [
  "Node.js Modules",
  "Node.js HTTP Module",
  "Node.js File System",
  "Node.js Path Module",
  "Node.js URL Module",
  "Node.js Query Strings",
  "Node.js NPM",
  "Node.js Events",
  "Node.js Streams",
  "Node.js Buffers",
  "Node.js Upload Files",
  "Node.js Email",
  "Node.js Middleware",
  "Node.js Debugging",
  "Node.js Error Handling",
  "Node.js REPL",
  "Node.js CLI",
  "Express.js Intro",
  "Express.js Routing",
  "Express.js Middleware",
  "Express.js Templates",
  "Express.js Forms",
  "Express.js REST API",
  "Express.js Authentication",
  "MySQL Get Started",
  "MySQL Create Database",
  "MySQL Create Table",
  "MySQL Insert Into",
  "MySQL Select From",
  "MySQL Where",
  "MySQL Order By",
  "MySQL Delete",
  "MySQL Drop Table",
  "MySQL Update",
  "MySQL Limit",
  "MySQL Join",
  "MongoDB Get Started",
  "MongoDB Create DB",
  "MongoDB Collection",
  "MongoDB Insert",
  "MongoDB Find",
  "MongoDB Query",
  "MongoDB Sort",
  "MongoDB Delete",
  "MongoDB Drop Collection",
  "MongoDB Update",
  "MongoDB Limit",
  "MongoDB Join",
  "MongoDB Aggregation",
  "RasPi Get Started",
  "RasPi GPIO Introduction",
  "RasPi Blinking LED",
  "RasPi LED & Pushbutton",
  "RasPi Flowing LEDs",
  "RasPi WebSocket",
  "RasPi RGB LED WebSocket",
  "RasPi Temperature Sensor",
  "RasPi Camera Module",
  "RasPi I2C Devices",
  "RasPi SPI Devices",
  "RasPi Components",
  "Built-in Modules",
  "Node.js Compiler",
  "Node.js Server",
  "Node.js Process",
  "Node.js Child Process",
  "Node.js Clustering",
  "Node.js File Uploads with Multer",
  "Node.js WebSockets",
  "Node.js JWT Authentication",
  "Node.js Passport.js",
  "Node.js Security Best Practices",
  "Node.js Performance Optimization",
];
