export const phpTopics = [
  "PHP Install",
  "PHP Syntax",
  "PHP Comments",
  "PHP Variables",
  "PHP Echo / Print",
  "PHP Data Types",
  "PHP Strings",
  "PHP Numbers",
  "PHP Casting",
  "PHP Math",
  "PHP Constants",
  "PHP Magic Constants",
  "PHP Operators",
  "PHP If...Else...Elseif",
  "PHP Switch",
  "PHP Loops",
  "PHP Functions",
  "PHP Arrays",
  "PHP Superglobals",
  "PHP RegEx",
  "PHP Form Handling",
  "PHP Form Validation",
  "PHP Form Required",
  "PHP Form URL/E-mail",
  "PHP Form Complete",
  "PHP Date and Time",
  "PHP Include",
  "PHP File Handling",
  "PHP File Open/Read",
  "PHP File Create/Write",
  "PHP File Upload",
  "PHP Cookies",
  "PHP Sessions",
  "PHP Filters",
  "PHP Filters Advanced",
  "PHP Callback Functions",
  "PHP JSON",
  "PHP Exceptions",
  "PHP What is OOP",
  "PHP Classes/Objects",
  "PHP Constructor",
  "PHP Destructor",
  "PHP Access Modifiers",
  "PHP Inheritance",
  "PHP Constants",
  "PHP Abstract Classes",
  "PHP Interfaces",
  "PHP Traits",
  "PHP Static Methods",
  "PHP Static Properties",
  "PHP Namespaces",
  "PHP Iterables",
  "MySQL Database",
  "MySQL Connect",
  "MySQL Create DB",
  "MySQL Create Table",
  "MySQL Insert Data",
  "MySQL Get Last ID",
  "MySQL Insert Multiple",
  "MySQL Prepared",
  "MySQL Select Data",
  "MySQL Where",
  "MySQL Order By",
  "MySQL Delete Data",
  "MySQL Update Data",
  "MySQL Limit Data",
  "PHP XML Parsers",
  "PHP SimpleXML Parser",
  "PHP SimpleXML - Get",
  "PHP XML Expat",
  "PHP XML DOM",
  "AJAX Intro",
  "AJAX PHP",
  "AJAX Database",
  "AJAX XML",
  "AJAX Live Search",
  "AJAX Poll",
  "PHP Examples",
  "PHP Compiler",
  "PHP Server",
  "PHP Syllabus",
  "PHP Study Plan",
  "PHP Certificate",
  "PHP Overview",
  "PHP Array",
  "PHP Calendar",
  "PHP Date",
  "PHP Directory",
  "PHP Error",
  "PHP Exception",
  "PHP Filesystem",
  "PHP Filter",
  "PHP FTP",
  "PHP JSON",
  "PHP Keywords",
  "PHP Libxml",
  "PHP Mail",
  "PHP Math",
  "PHP Misc",
  "PHP MySQLi",
  "PHP Network",
  "PHP Output Control",
  "PHP RegEx",
  "PHP SimpleXML",
  "PHP Stream",
  "PHP String",
  "PHP Variable Handling",
  "PHP XML Parser",
  "PHP Zip",
  "PHP Timezones"
];
